#!/bin/sh

. /usr/lib/live/config.sh

Cmdline ()
{
	for _PARAMETER in ${LIVE_CONFIG_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.username=*|username=*)
				LIVE_USERNAME="${_PARAMETER#*username=}"
				;;
		esac
	done
}

Init ()
{
	if ! pkg_is_installed "passwd" || \
	   component_was_executed "9020-fix-password"
	then
		exit 0
	fi

	echo -n " fix-password"
}

Config ()
{
	if [ -n "${LIVE_USERNAME}" ] && id "${LIVE_USERNAME}" >/dev/null 2>&1; then
		echo "${LIVE_USERNAME}:${LIVE_USERNAME}" | chpasswd 2>/dev/null || true
	fi

	touch /var/lib/live/config/9020-fix-password
}

Cmdline
Init
Config
